BookPortfolio/Controllers/BookController.cs
using BookPortfolio.Data;
using BookPortfolio.Dtos.Book;
using BookPortfolio.Interfaces;
using BookPortfolio.Mappers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookPortfolio.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IBookRepository _bookRepository;

        public BookController(ApplicationDbContext context, IBookRepository bookRepository)
        {
            _context = context;
            _bookRepository = bookRepository;
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var books = _context.books.ToList();
            return View(books);
        }

        // Post
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateBookRequestDto model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            var bookModel = model.ToBookFromCreateDto();
            await _bookRepository.CreateAsync(bookModel);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> SearchResults([FromQuery] Helpers.BookQueryHelper query)
        {
            if (!ModelState.IsValid)
            {
                return View(query);
            }
            var books = await _bookRepository.GetAllAsync(query);
            var bookDto = books.Select(b => b.ToBookDto()).ToList();
            Console.WriteLine("Found " + books.Count + " books with the query " + query.SearchTerm);
            return View(books);
        }

        [HttpGet]
        public async Task<IActionResult> BookView(int BookId)
        {

            var book = await _bookRepository.GetByIdAsync(BookId);
            if (book != null)
            {
                return View(book);

            }
            else
            {
                return StatusCode(500, "Book Not Found");
            }
        }

    }
}

BookPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookPortfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookPortfolio.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookPortfolio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
						<li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="Portfolio" asp-action="Index">Your Portfolio</a>
						</li>
                    </ul>
                    @Html.Partial("_SearchPartial", ViewData["SearchQuery"])
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - BookPortfolio - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookPortfolio/Views/Shared/_SearchPartial.cshtml
@model BookPortfolio.Helpers.BookQueryHelper
@using (Html.BeginForm("SearchResults", "Book", FormMethod.Get))
{
    @Html.TextBoxFor(m => m.SearchTerm)

    <div>
        <input type="submit" value="Search" />
    </div>
}